language: java
sudo: false
jdk:
  - oraclejdk8
before_script:
  - wget http://services.gradle.org/distributions/gradle-3.1-bin.zip
  - unzip gradle-3.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-3.1
  - export PATH=$GRADLE_HOME/bin:$PATH
script:
  - TERM=dumb
  - gradle -v
  - gradle check jacocoTestReport
after_success:
  - gradle jacocoRootReport coveralls
notifications:
  email: false